In [141]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [142]:
!pip install pdfplumber 


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [143]:
!pip install ocrmypdf -q   #installing OCR library 

In [144]:
import pdfplumber
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords 
from string import punctuation
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist
from heapq import nlargest
from collections import defaultdict
import pandas as pd 
from nltk.collocations import *
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [145]:
with pdfplumber.open("test.pdf") as pdf:
    text=""
    pages = pdf.pages
    for page in pages:
        text += page.extract_text(x_tolerance=2)
        print(text)

Anudeep 
Sr Java Programmer 
anudeepreddynallamada@gmail.com 
PROFESSIONAL SUMMARY: 
• IT professional with 8+ years of IT experience in designing and developing N-tier applications based on 
OOPS (Object Oriented Programming), Internet and Intranet, Client-Server Architecture using Java/J2EE 
and supporting technologies. 
•  Strong Experience in developing user interfaces with HTML, DHTML, XML and CSS.  
• Experienced in processing, validating, parsing and extracting data from .xml file.  
•  Worked with scripting languages like JavaScript, JQuery.  
•  Well versed in MVC (Model View Controller) architecture using Spring, JSF and implementing JSTL (JSP 
Standard Tag Library), custom tag development and tiles.  
•  Experience in JSP, Java Beans and Servlets for developing applications using MVC architecture.  
•  Good exposure in implementing web services-WSDL using SOAP protocol.  
•  Experienced in Persistence Framework like Hibernate ORM (Object Relational Mapping) in a typical n-
t

# Import CV and scraped data

In [146]:
# Import CV

f=open('test.txt','r', errors = 'ignore')
text=f.read()

# Locations
f1=open('india_districts.txt','r', errors = 'ignore')
text1=f1.read()
locations = word_tokenize(text1.replace("\n", " "))

# Additional stopwords
f2=open('stopwords.txt','r', errors = 'ignore')
text2=f2.read()
stopwords_additional = word_tokenize(text2.replace("\n", " "))

In [147]:
def nlp(x):
    word_sent = word_tokenize(x.lower().replace("\n",""))
    _stopwords = set(stopwords.words('english') + list(punctuation)+list("●")+list('–')+list('’')+locations+stopwords_additional)
    word_sent=[word for word in word_sent if word not in _stopwords]
    lemmatizer = WordNetLemmatizer()
    NLP_Processed_CV = [lemmatizer.lemmatize(word) for word in word_tokenize(" ".join(word_sent))]
    # return " ".join(NLP_Processed_CV)
    return NLP_Processed_CV

In [148]:
 nltk.download('omw-1.4')   

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [149]:
NLP_Processed_CV = nlp(text)
# NLP_Processed_CV=' '.join(NLP_Processed_CV)
NLP_Processed_CV

['anudeep',
 'sr',
 'java',
 'programmer',
 'anudeepreddynallamada',
 'gmail.com',
 'professional',
 'summary',
 '•',
 'professional',
 '8+',
 'experience',
 'designing',
 'developing',
 'n-tier',
 'application',
 'based',
 'oops',
 'object',
 'oriented',
 'programming',
 'internet',
 'intranet',
 'client-server',
 'architecture',
 'using',
 'java/j2ee',
 'supporting',
 'technology',
 '•',
 'strong',
 'experience',
 'developing',
 'user',
 'interface',
 'html',
 'dhtml',
 'xml',
 'cs',
 '•',
 'experienced',
 'processing',
 'validating',
 'parsing',
 'extracting',
 'data',
 '.xml',
 'file',
 '•',
 'scripting',
 'language',
 'javascript',
 'jquery',
 '•',
 'versed',
 'mvc',
 'model',
 'view',
 'controller',
 'architecture',
 'using',
 'spring',
 'jsf',
 'implementing',
 'jstl',
 'jsp',
 'standard',
 'tag',
 'library',
 'custom',
 'tag',
 'development',
 'tile',
 '•',
 'experience',
 'jsp',
 'java',
 'bean',
 'servlets',
 'developing',
 'application',
 'using',
 'mvc',
 'architecture',
 '

In [150]:
def get_key_word(x):
    finder = BigramCollocationFinder.from_words(x)
    lst = []
    Key_word_from_CV = []
    for i in sorted(finder.ngram_fd.items()):
    # if a double word appears more than once, then print it out.
        if i[1] > 1:
            print(i)
            lst.append(i[0])
        else:
            pass

    # print("************************")
    for j in lst:
    #     print(" ".join(j))
        Key_word_from_CV.append(" ".join(j))
    return Key_word_from_CV

In [151]:
key_word = get_key_word(NLP_Processed_CV)
key_word

(('-the-fly', 'configuration'), 3)
(('-till', 'date'), 4)
(('.xml', 'file'), 5)
(('/10g,11g', 'hsql'), 4)
(('1.3', '1.4'), 2)
(('1.4', 'using'), 2)
(('2.0', 'mobile'), 4)
(('2.0', 'standard'), 3)
(('2.0.47', 'ihs'), 3)
(('2.5', 'mvc'), 2)
(('2000', 'professional'), 5)
(('2003', 'server'), 5)
(('2009', 'technical'), 5)
(('2012', 'july2014'), 2)
(('2014', 'aug'), 3)
(('2015', 'role'), 3)
(('2015–aug', '2016'), 3)
(('2016', 'role'), 3)
(('6.0', 'apache'), 3)
(('6.0', 'window'), 3)
(('6.0/6.1', 'academic'), 3)
(('6.0/6.1', 'websphere'), 3)
(('6.0/6.1', '•'), 3)
(('6.0/6.1/7.0', 'websphere'), 3)
(('8+', 'experience'), 5)
(('9.design', 'pattern'), 4)
(('9/10', 'red'), 4)
(('95/98/nt/2000/xp', 'sun'), 4)
(('9i', '/10g,11g'), 4)
(('academic', 'bank'), 3)
(('access', 'display'), 3)
(('access', 'manager'), 2)
(('accessibility', 'web'), 3)
(('accommodate', 'advanced'), 2)
(('achieved', 'proficiency'), 3)
(('act', 'front'), 3)
(('actively', 'participated'), 2)
(('add', 'feature'), 2)
(('add', 'mod

['-the-fly configuration',
 '-till date',
 '.xml file',
 '/10g,11g hsql',
 '1.3 1.4',
 '1.4 using',
 '2.0 mobile',
 '2.0 standard',
 '2.0.47 ihs',
 '2.5 mvc',
 '2000 professional',
 '2003 server',
 '2009 technical',
 '2012 july2014',
 '2014 aug',
 '2015 role',
 '2015–aug 2016',
 '2016 role',
 '6.0 apache',
 '6.0 window',
 '6.0/6.1 academic',
 '6.0/6.1 websphere',
 '6.0/6.1 •',
 '6.0/6.1/7.0 websphere',
 '8+ experience',
 '9.design pattern',
 '9/10 red',
 '95/98/nt/2000/xp sun',
 '9i /10g,11g',
 'academic bank',
 'access display',
 'access manager',
 'accessibility web',
 'accommodate advanced',
 'achieved proficiency',
 'act front',
 'actively participated',
 'add feature',
 'add modal',
 'admin console',
 'admin server',
 'administered websphere',
 'adobe flash',
 'adopted wcag',
 'advanced fast',
 'agile methodology',
 'agile scrum',
 'ajax increase',
 'ajax javascript',
 'analysis design',
 'analytics using',
 'angular j',
 'angular.js development',
 'angular.js node.js',
 'angularj

In [152]:
#Import scraped data
df = pd.read_csv("final_sample.csv", on_bad_lines='warn', engine="python")
df.head(5)

JobID                                    job description  \
0  J001  TeamSoft is seeing an IT Support Specialist to...   
1  J002  The Wisconsin State Journal is seeking a flexi...   
2  J003  Report this job About the Job DePuy Synthes Co...   
3  J004  Why Join Altec? If you’re considering a career...   
4  J005  Position ID#  76162 # Positions  1 State  CT C...   

                                               title     company overview  \
0               IT Support Technician Job in Madison   Full Time Employee   
1            Business Reporter/Editor Job in Madison            Full Time   
2  Johnson & Johnson Family of Companies Job Appl...  Full Time, Employee   
3                    Engineer - Quality Job in Dixon            Full Time   
4       Shift Supervisor - Part-Time Job in Camphill   Full Time Employee   

                                            location  \
0                                  Madison, WI 53702   
1                                  Madison, WI 53708   
2  DePuy Synthes Companies is a member of Johnson...   
3                                          Dixon, CA   
4                                       Camphill, PA   

                      organization salary                    industry  \
0                              NaN    NaN     IT/Software Development   
1          Printing and Publishing    NaN                         NaN   
2  Personal and Household Services    NaN                         NaN   
3                 Altec Industries    NaN   Experienced (Non-Manager)   
4                           Retail    NaN  Project/Program Management   

                                                 All  
0  TeamSoft is seeing an IT Support Specialist to...  
1  The Wisconsin State Journal is seeking a flexi...  
2  Report this job About the Job DePuy Synthes Co...  
3  Why Join Altec? If you’re considering a career...  
4  Position ID#  76162 # Positions  1 State  CT C...

In [153]:
# print(NLP_Processed_CV)
# print(key_word)
df.shape

(100, 9)

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   JobID             100 non-null    object
 1   job description   100 non-null    object
 2   title             100 non-null    object
 3   company overview  93 non-null     object
 4   location          100 non-null    object
 5   organization      62 non-null     object
 6   salary            21 non-null     object
 7   industry          73 non-null     object
 8   All               100 non-null    object
dtypes: object(9)
memory usage: 7.2+ KB


# Put keyword/CV into a dataframe

In [155]:
df2 = pd.DataFrame()
# append columns to an empty DataFrame
df2['title'] = ["I"]
df2['job highlights'] = ["I"]
df2['job description'] = ["I"]
df2['company overview'] = ["I"]
df2['industry'] = ["I"]

# Compare with the key words from CV only
df2['All'] = " ".join(key_word)

# Compare with the entire CV
# df2['All'] = " ".join(NLP_Processed_CV)
# df2

# Create get_recommendation function

In [156]:
def get_recommendation(top, df_all, scores):
    recommendation = pd.DataFrame(columns = ['JobID',  'title', 'industry', 'job description','score'])
    count = 0
    for i in top:
#         recommendation.at[count, 'ApplicantID'] = u
        recommendation.at[count, 'JobID'] = df.index[i]
        recommendation.at[count, 'title'] = df['title'][i]
        recommendation.at[count, 'industry'] = df['industry'][i]
#         recommendation.at[count, 'location'] = df['location'][i]
        recommendation.at[count, 'job description'] = df['job description'][i]
        recommendation.at[count, 'score'] =  scores[count]
        count += 1
    return recommendation

# TFIDF

In [157]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer


def TFIDF(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    # TF-IDF Scraped data
    # x = v.fit_transform(df['Review'].apply(lambda x: np.str_(x)))
    tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data.apply(lambda tfidf_jobid: np.str_(tfidf_jobid)))

    # TF-IDF CV
    user_tfidf = tfidf_vectorizer.transform(cv)

    # Using cosine_similarity on (Scraped data) & (CV)
    cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)

    output2 = list(cos_similarity_tfidf)
    return output2
    
output2 = TFIDF(df['All'], df2['All'])
output2

[array([[0.02657497]]),
 array([[0.02957909]]),
 array([[0.05152631]]),
 array([[0.03468288]]),
 array([[0.01848572]]),
 array([[0.06520974]]),
 array([[0.12129616]]),
 array([[0.03618113]]),
 array([[0.01122265]]),
 array([[0.05104894]]),
 array([[0.02197753]]),
 array([[0.01570537]]),
 array([[0.02041663]]),
 array([[0.01165873]]),
 array([[0.02374321]]),
 array([[0.0437821]]),
 array([[0.02289673]]),
 array([[0.04074271]]),
 array([[0.08792676]]),
 array([[0.05599213]]),
 array([[0.08050341]]),
 array([[0.02445581]]),
 array([[0.01936605]]),
 array([[0.06756896]]),
 array([[0.02655289]]),
 array([[0.01209288]]),
 array([[0.05598489]]),
 array([[0.03971525]]),
 array([[0.00744881]]),
 array([[0.04811137]]),
 array([[0.0547273]]),
 array([[0.0261201]]),
 array([[0.06703221]]),
 array([[0.00446226]]),
 array([[0.08221048]]),
 array([[0.07946948]]),
 array([[0.04819562]]),
 array([[0.03706975]]),
 array([[0.08289201]]),
 array([[0.12608106]]),
 array([[0.02601251]]),
 array([[0.01439516

In [158]:
top = sorted(range(len(output2)), key=lambda i: output2[i], reverse=True)[:100]
list_scores = [output2[i][0][0] for i in top]
TF=get_recommendation(top,df, list_scores)
TF

JobID                                              title  \
0     95                         Scrum Master Job in Denver   
1     53                Software Engineer Job in Fort Wayne   
2     39  Software Engineer - Display Solutions Group Jo...   
3      6  CyberCoders Job Application for Principal QA E...   
4     93      Custom Development Engineer Job in Greenville   
..   ...                                                ...   
95    70   Hotel Construction Superintendent Job in Houston   
96    45  Respiratory Therapist PRN Nights - Kindred Hos...   
97    28                           Resident Care Specialist   
98    52  Elementary English Language Acquisition – Span...   
99    33                   Equipment Operator Job in Denver   

                   industry  \
0   IT/Software Development   
1               Engineering   
2                       NaN   
3                       NaN   
4               Engineering   
..                      ...   
95                      NaN   
96           Medical/Health   
97                      NaN   
98                      NaN   
99                      NaN   

                                      job description     score  
0   The Judge Group is looking for a Scrum Master ...  0.205616  
1   A Fortune 500 and worldwide leader in business...  0.174883  
2   ResponsibilitiesCandidate will participate in ...  0.126081  
3   Report this job About the Job Based in San Fra...  0.121296  
4   About Agfa HealthCare   Agfa HealthCare, a mem...  0.101341  
..                                                ...       ...  
95  Houston based General Contractor with 20 years...  0.010664  
96  Respiratory Therapist PRN Nights - Kindred Hos...  0.007983  
97  Resident Care Specialist DescriptionSummaryPro...  0.007449  
98  Elementary English  Language Acquisition – Spa...  0.006255  
99  Construction                                  ...  0.004462  

[100 rows x 5 columns]

# Count Vectorizer

In [159]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

count_vectorizer = CountVectorizer()
count_jobid = count_vectorizer.fit_transform(df['All'].apply(lambda count_jobid: np.str_(count_jobid))) #fitting and transforming the vector
count_jobid


<100x5243 sparse matrix of type '<class 'numpy.int64'>'
	with 20060 stored elements in Compressed Sparse Row format>

In [160]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def count_vectorize(scraped_data, cv):
    # CountV the scraped data
    count_vectorizer = CountVectorizer()
    count_jobid = count_vectorizer.fit_transform(scraped_data.apply(lambda count_jobid: np.str_(count_jobid))) #fitting and transforming the vector

    # CountV the cv
    user_count = count_vectorizer.transform(cv)
    cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
    output3 = list(cos_similarity_countv)
    return output3
output3 = count_vectorize(df['All'], df2['All'])
output3

[array([[0.05133426]]),
 array([[0.04552007]]),
 array([[0.06051582]]),
 array([[0.04533373]]),
 array([[0.0316139]]),
 array([[0.07473813]]),
 array([[0.13205722]]),
 array([[0.04571678]]),
 array([[0.02922354]]),
 array([[0.05219548]]),
 array([[0.04158535]]),
 array([[0.03187833]]),
 array([[0.03605834]]),
 array([[0.0255263]]),
 array([[0.04271993]]),
 array([[0.05683885]]),
 array([[0.03322121]]),
 array([[0.04456734]]),
 array([[0.07753377]]),
 array([[0.05203844]]),
 array([[0.0901623]]),
 array([[0.03986846]]),
 array([[0.03196113]]),
 array([[0.04781308]]),
 array([[0.04593086]]),
 array([[0.03442472]]),
 array([[0.05503198]]),
 array([[0.04674823]]),
 array([[0.01789144]]),
 array([[0.06184268]]),
 array([[0.08725511]]),
 array([[0.05381022]]),
 array([[0.05665558]]),
 array([[0.03034671]]),
 array([[0.07724833]]),
 array([[0.06886401]]),
 array([[0.05901206]]),
 array([[0.04904167]]),
 array([[0.08619283]]),
 array([[0.14358917]]),
 array([[0.04908942]]),
 array([[0.03551261

In [161]:
# print(count_jobid)

In [162]:
user_count = count_vectorizer.transform(df2['All'])
user_count

<1x5243 sparse matrix of type '<class 'numpy.int64'>'
	with 269 stored elements in Compressed Sparse Row format>

In [163]:
print(user_count)

  (0, 16)	2
  (0, 68)	4
  (0, 71)	2
  (0, 73)	2
  (0, 74)	4
  (0, 75)	4
  (0, 236)	2
  (0, 245)	4
  (0, 249)	2
  (0, 283)	2
  (0, 289)	2
  (0, 302)	4
  (0, 329)	3
  (0, 336)	2
  (0, 375)	5
  (0, 438)	2
  (0, 443)	2
  (0, 474)	4
  (0, 480)	43
  (0, 512)	6
  (0, 539)	2
  (0, 637)	5
  (0, 641)	2
  (0, 645)	2
  (0, 654)	2
  :	:
  (0, 4773)	2
  (0, 4894)	2
  (0, 4895)	2
  (0, 4918)	2
  (0, 4933)	2
  (0, 4961)	2
  (0, 4966)	4
  (0, 4975)	2
  (0, 4978)	2
  (0, 4979)	2
  (0, 4997)	10
  (0, 5002)	5
  (0, 5005)	73
  (0, 5009)	4
  (0, 5021)	2
  (0, 5022)	4
  (0, 5028)	2
  (0, 5036)	4
  (0, 5053)	3
  (0, 5067)	5
  (0, 5076)	3
  (0, 5107)	2
  (0, 5128)	41
  (0, 5129)	4
  (0, 5167)	14


In [164]:
cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
output3 = list(cos_similarity_countv)
# output3

In [165]:
# output3 = count_vectorize(df['All'], df2['All'])
# output3

In [166]:
top = sorted(range(len(output3)), key=lambda i: output3[i], reverse=True)[:100]
list_scores = [output3[i][0][0] for i in top]
cv=get_recommendation(top, df, list_scores)
cv

JobID                                              title  \
0     95                         Scrum Master Job in Denver   
1     39  Software Engineer - Display Solutions Group Jo...   
2      6  CyberCoders Job Application for Principal QA E...   
3     93      Custom Development Engineer Job in Greenville   
4     53                Software Engineer Job in Fort Wayne   
..   ...                                                ...   
95    68          Local/Delivery Truck Driver Job in Denver   
96    45  Respiratory Therapist PRN Nights - Kindred Hos...   
97    59      Technical Writer - Documentation Job in Ogden   
98    28                           Resident Care Specialist   
99    52  Elementary English Language Acquisition – Span...   

                     industry  \
0     IT/Software Development   
1                         NaN   
2                         NaN   
3                 Engineering   
4                 Engineering   
..                        ...   
95  Experienced (Non-Manager)   
96             Medical/Health   
97          Editorial/Writing   
98                        NaN   
99                        NaN   

                                      job description     score  
0   The Judge Group is looking for a Scrum Master ...  0.209033  
1   ResponsibilitiesCandidate will participate in ...  0.143589  
2   Report this job About the Job Based in San Fra...  0.132057  
3   About Agfa HealthCare   Agfa HealthCare, a mem...  0.130475  
4   A Fortune 500 and worldwide leader in business...  0.125267  
..                                                ...       ...  
95  Job Purpose:Delivers items by preparing, loadi...  0.023559  
96  Respiratory Therapist PRN Nights - Kindred Hos...  0.019474  
97  Maden Technologies is accepting applications f...  0.019263  
98  Resident Care Specialist DescriptionSummaryPro...  0.017891  
99  Elementary English  Language Acquisition – Spa...  0.016714  

[100 rows x 5 columns]

# KNN

In [167]:
# !pip uninstall scikit-learn -y
# !pip install scikit-learn==0.24.1

In [168]:
from sklearn.neighbors import NearestNeighbors

def KNN(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    # n_neighbors = 100
    KNN = NearestNeighbors(n_neighbors=100, p=2)
    #  count_jobid = count_vectorizer.fit_transform(scraped_data.apply(lambda count_jobid: np.str_(count_jobid))) 
    x= tfidf_vectorizer.fit_transform(scraped_data.apply(lambda x: np.str_(x)))
    KNN.fit(x)
    # KNN.fit(tfidf_vectorizer.fit_transform(scraped_data))
#     NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv), return_distance=True)
    NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv))
    top = NNs[1][0][1:]
    index_score = NNs[0][0][1:]

    knn = get_recommendation(top, df, index_score)
    return knn

knn = KNN(df['All'], df2['All'])
knn

JobID                                              title  \
0     53                Software Engineer Job in Fort Wayne   
1     39  Software Engineer - Display Solutions Group Jo...   
2      6  CyberCoders Job Application for Principal QA E...   
3     93      Custom Development Engineer Job in Greenville   
4     18  Content Developer for MATLAB Code Generation J...   
..   ...                                                ...   
94    70   Hotel Construction Superintendent Job in Houston   
95    45  Respiratory Therapist PRN Nights - Kindred Hos...   
96    28                           Resident Care Specialist   
97    52  Elementary English Language Acquisition – Span...   
98    33                   Equipment Operator Job in Denver   

                     industry  \
0                 Engineering   
1                         NaN   
2                         NaN   
3                 Engineering   
4   Experienced (Non-Manager)   
..                        ...   
94                        NaN   
95             Medical/Health   
96                        NaN   
97                        NaN   
98                        NaN   

                                      job description     score  
0   A Fortune 500 and worldwide leader in business...  1.284614  
1   ResponsibilitiesCandidate will participate in ...  1.322058  
2   Report this job About the Job Based in San Fra...  1.325673  
3   About Agfa HealthCare   Agfa HealthCare, a mem...  1.340641  
4   Job SummaryDo you have a strong aptitude for w...   1.35061  
..                                                ...       ...  
94  Houston based General Contractor with 20 years...  1.406653  
95  Respiratory Therapist PRN Nights - Kindred Hos...  1.408557  
96  Resident Care Specialist DescriptionSummaryPro...  1.408937  
97  Elementary English  Language Acquisition – Spa...  1.409783  
98  Construction                                  ...  1.411055  

[99 rows x 5 columns]

In [169]:
knn.to_csv('knn.csv', index=False)

# Combined TFIDF, CV and KNN result together, to make a dataframe "final"

In [170]:
# merge1 = knn[['JobID','title', 'score']].merge(TF[['JobID','score']], on= "JobID")
# final = merge1.merge(cv[['JobID','score']], on = "JobID")
# final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
# final.head()

merge1 = knn[['JobID','title', 'score']].merge(TF[['JobID','score']], on= "JobID")
final = merge1.merge(cv[['JobID','score']], on = "JobID")
final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
final.head()

JobID                                              title       KNN  \
0    53                Software Engineer Job in Fort Wayne  1.284614   
1    39  Software Engineer - Display Solutions Group Jo...  1.322058   
2     6  CyberCoders Job Application for Principal QA E...  1.325673   
3    93      Custom Development Engineer Job in Greenville  1.340641   
4    18  Content Developer for MATLAB Code Generation J...   1.35061   

     TF-IDF        CV  
0  0.174883  0.125267  
1  0.126081  0.143589  
2  0.121296  0.132057  
3  0.101341  0.130475  
4  0.087927  0.077534

In [171]:
# high = max(knn['score'])
# def reverseScoring(df, high, cols):
#     '''Reverse scores on given columns
#      df = your data frame,
#      high = highest score available
#      cols = the columns you want reversed in list form'''
#     df[cols] = high - df[cols]
# #     return df['score']
#     return df
# reverseScoring(knn, high, 'score')

In [172]:
# reverseScoring(knn, high, 'score').to_csv('test.csv', index=False)

# Scale and assign weights

In [173]:
# Scale it
from sklearn.preprocessing import MinMaxScaler
slr = MinMaxScaler()
# round(final['KNN'],9)
final[["KNN", "TF-IDF", 'CV']] = slr.fit_transform(final[["KNN", "TF-IDF", 'CV']])

# Multiply by weights
final['KNN'] = (1-final['KNN'])/3
final['TF-IDF'] = final['TF-IDF']/3
final['CV'] = final['CV']/3
final['Final'] = final['KNN']+final['TF-IDF']+final['CV']
final.sort_values(by="Final", ascending=False)

JobID                                              title       KNN  \
0     53                Software Engineer Job in Fort Wayne  0.333333   
1     39  Software Engineer - Display Solutions Group Jo...  0.234621   
2      6  CyberCoders Job Application for Principal QA E...  0.225092   
3     93      Custom Development Engineer Job in Greenville  0.185631   
10    94               Electrical Engineer Job in Budd Lake  0.141152   
..   ...                                                ...       ...   
91    13  Primrose Private Preschool Teacher Job in Houston  0.013470   
98    33                   Equipment Operator Job in Denver  0.000000   
95    45  Respiratory Therapist PRN Nights - Kindred Hos...  0.006583   
96    28                           Resident Care Specialist  0.005584   
97    52  Elementary English Language Acquisition – Span...  0.003351   

      TF-IDF        CV     Final  
0   0.333333  0.285196  0.951863  
1   0.237880  0.333333  0.805834  
2   0.228521  0.303036  0.756649  
3   0.189489  0.298879  0.673999  
10  0.144969  0.263771  0.549892  
..       ...       ...       ...  
91  0.014076  0.023152  0.050698  
98  0.000000  0.035817  0.035817  
95  0.006886  0.007253  0.020722  
96  0.005842  0.003093  0.014519  
97  0.003507  0.000000  0.006859  

[99 rows x 6 columns]

In [174]:
# final.to_csv('final.csv', index=False)
final2 = final.sort_values(by="Final", ascending=False).copy()
final2

JobID                                              title       KNN  \
0     53                Software Engineer Job in Fort Wayne  0.333333   
1     39  Software Engineer - Display Solutions Group Jo...  0.234621   
2      6  CyberCoders Job Application for Principal QA E...  0.225092   
3     93      Custom Development Engineer Job in Greenville  0.185631   
10    94               Electrical Engineer Job in Budd Lake  0.141152   
..   ...                                                ...       ...   
91    13  Primrose Private Preschool Teacher Job in Houston  0.013470   
98    33                   Equipment Operator Job in Denver  0.000000   
95    45  Respiratory Therapist PRN Nights - Kindred Hos...  0.006583   
96    28                           Resident Care Specialist  0.005584   
97    52  Elementary English Language Acquisition – Span...  0.003351   

      TF-IDF        CV     Final  
0   0.333333  0.285196  0.951863  
1   0.237880  0.333333  0.805834  
2   0.228521  0.303036  0.756649  
3   0.189489  0.298879  0.673999  
10  0.144969  0.263771  0.549892  
..       ...       ...       ...  
91  0.014076  0.023152  0.050698  
98  0.000000  0.035817  0.035817  
95  0.006886  0.007253  0.020722  
96  0.005842  0.003093  0.014519  
97  0.003507  0.000000  0.006859  

[99 rows x 6 columns]

In [175]:
final2.head(10)

JobID                                              title       KNN  \
0     53                Software Engineer Job in Fort Wayne  0.333333   
1     39  Software Engineer - Display Solutions Group Jo...  0.234621   
2      6  CyberCoders Job Application for Principal QA E...  0.225092   
3     93      Custom Development Engineer Job in Greenville  0.185631   
10    94               Electrical Engineer Job in Budd Lake  0.141152   
7     20         Business & Strategy Analyst Job in Houston  0.144890   
5     38  Bi-Lingual Editorial Strategist Job in San Fra...  0.149537   
4     18  Content Developer for MATLAB Code Generation J...  0.159351   
8     66               Development Associate Job in Houston  0.144608   
6     34     Associate Product Developer Job in Saint Louis  0.148210   

      TF-IDF        CV     Final  
0   0.333333  0.285196  0.951863  
1   0.237880  0.333333  0.805834  
2   0.228521  0.303036  0.756649  
3   0.189489  0.298879  0.673999  
10  0.144969  0.263771  0.549892  
7   0.148732  0.192967  0.486590  
5   0.153404  0.182539  0.485480  
4   0.163252  0.159789  0.482392  
8   0.148449  0.172631  0.465688  
6   0.152071  0.159039  0.459321

In [178]:
# duplicate = df[df.duplicated()]
# duplicate
# a = np.intersect1d(df.columns, final2.columns)
# a

In [183]:
final2.merge(df, on="JobID")
# final_salary = df.merge(final2, on="JobID")
final_salary

Empty DataFrame
Columns: [JobID, job description, title_x, company overview, location, organization, salary, industry, All, title_y, KNN, TF-IDF, CV, Final]
Index: []